-- phpMyAdmin SQL Dump
-- version 5.2.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Aug 10, 2026 at 04:37 AM
-- Server version: 8.4.3
-- PHP Version: 8.3.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cms`
--

-- --------------------------------------------------------

--
-- Table structure for table `pages`
--

CREATE TABLE `pages` (
  `id` int NOT NULL,
  `name` text NOT NULL,
  `slug` text NOT NULL,
  `text` mediumtext,
  `author` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `date_published` datetime DEFAULT NULL,
  `date_updated` datetime DEFAULT NULL,
  `image_url` varchar(500) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `pages`
--

INSERT INTO `pages` (`id`, `name`, `slug`, `text`, `author`, `date_published`, `date_updated`, `image_url`) VALUES
(83, 'Ceres Relay Station Goes Live', 'ceres-relay-station-goes-live', 'Ceres, 4 Sol-January 2026. The long-awaited deep-space relay station orbiting the dwarf planet has begun routing traffic between the inner colonies and the outer survey fleets. Engineers spent three years assembling the modular array in vacuum, and its activation cuts message lag to the asteroid belt by nearly a third. Officials call it a quiet revolution for commerce and science alike, binding scattered outposts into a single conversation that no longer waits hours for a reply across the dark.', 'super.admin@email.com', '2026-01-11 08:30:00', '2026-01-11 08:30:00', '/storage/2.webp'),
(84, 'Frost Line Farming Yields Surprise Crop', 'frost-line-farming-surprise-crop', 'Utopia Planitia, 22 Sol-January 2026. Agronomists working the coldest edge of the northern domes have coaxed a hardy root vegetable to thrive where nothing was expected to grow. The strain, engineered over six seasons, tolerates temperature swings that would kill ordinary crops overnight. Settlement kitchens are already experimenting with the harvest, and planners see it as a way to push farming into regions long written off as barren. For a world obsessed with self-sufficiency, every new crop is a small victory.', 'admin@admin', '2026-01-28 14:10:00', '2026-01-28 14:10:00', '/storage/4.webp'),
(86, 'Orbital Foundry Casts First Beam', 'orbital-foundry-casts-first-beam', 'Mars Orbit, 19 Sol-February 2026. High above the surface, a zero-gravity foundry has poured its first structural beam, drawn from metal mined on Phobos. Freed from gravity, the metal cools into shapes impossible to forge on the ground, longer and lighter than anything a planetary factory could produce. The beam will anchor the next orbital habitat. Engineers describe the moment as the true beginning of building in space, no longer hauling materials up a gravity well at ruinous cost.', 'super.admin@email.com', '2026-02-19 14:10:00', '2026-02-19 14:10:00', '/storage/3.webp'),
(87, 'Language Drift Study Splits Linguists', 'language-drift-study-splits-linguists', 'New Kasei, 2 Sol-March 2026. A study tracking how settlement speech has diverged from Earth tongues has ignited debate among scholars. Younger colonists, researchers find, have coined hundreds of words for phenomena Earth never named, from dust-light to the particular ache of low gravity. Some linguists celebrate a language coming into its own; others fear the drift will one day make the two worlds strangers. Either way, the Martian voice is no longer an echo of the planet it left behind.', 'admin@admin', '2026-03-02 09:45:00', '2026-03-02 09:45:00', '/storage/2.webp'),
(89, 'Archive Ship Returns From Earth', 'archive-ship-returns-from-earth', 'Chryse Planitia, 28 Sol-March 2026. A cargo vessel has arrived bearing a vast archive of Earth\'s art, music, and history, requested by settlements eager to preserve their heritage for children who will never visit the home world. Curators are already planning galleries and listening rooms. The shipment weighs almost nothing yet carries centuries of human culture in its data cores. For a society building its own traditions, the archive is both a link to the past and raw material for whatever comes next.', 'super.admin@email.com', '2026-03-28 13:40:00', '2026-03-28 13:40:00', '/storage/1.webp'),
(90, 'Gravity Clinic Reports Breakthrough', 'gravity-clinic-reports-breakthrough', 'Tharsis, 8 Sol-April 2026. A clinic specializing in the ailments of low-gravity life has announced a treatment that restores muscle density lost over years on Mars. Early patients, many of them elderly pioneers, report walking unaided for the first time in seasons. The therapy pairs targeted exercise with a compound developed on-world, a point of pride for local researchers. If it holds up in wider trials, it could transform the prospects of aging in a place the human body was never built for.', 'admin@admin', '2026-04-08 16:05:00', '2026-04-08 16:05:00', '/storage/3.webp'),
(92, 'Deep Drill Reaches Ancient Aquifer', 'deep-drill-reaches-ancient-aquifer', 'Meridiani Planum, 3 Sol-May 2026. A drilling rig has struck a reservoir of liquid water far beneath the surface, kept unfrozen by the planet\'s inner warmth. The find could supply a growing settlement for a century and reshape plans for expansion across the flats. Geologists marvel that the water has waited billions of years in the dark. Mining interests are already circling, and the discovery is likely to test the same water-rights laws that have divided the colonies for a generation.', 'super.admin@email.com', '2026-05-03 11:20:00', '2026-05-03 11:20:00', '/storage/4.webp'),
(93, 'Robotics Fair Draws Record Crowds', 'robotics-fair-draws-record-crowds', 'New Kasei, 16 Sol-May 2026. The annual robotics fair filled its dome to capacity as inventors showed off machines built to survive dust, cold, and vacuum. Student teams competed alongside industry giants, and one homemade rover drew gasps by scaling a wall of loose regolith. The fair has become a proving ground for the tools that keep the settlements alive. Judges say the ingenuity on display, much of it from the Martian-born, points to a future where the colonies invent as much as they import.', 'admin@admin', '2026-05-16 14:30:00', '2026-05-16 14:30:00', '/storage/1.webp'),
(95, 'Trade Council Signs Belt Accord', 'trade-council-signs-belt-accord', 'Tharsis, 11 Sol-June 2026. Delegates have signed a landmark accord opening regular trade routes between Mars and the asteroid belt outposts. The agreement fixes prices for ore and water and promises steadier supplies to both sides. Negotiations dragged for months over shipping rights, but the final handshake was met with relief. Merchants expect the deal to lower costs across the inner system. For settlements long dependent on Earth, a thriving belt trade offers a second lifeline and a taste of independence.', 'super.admin@email.com', '2026-06-11 13:05:00', '2026-06-11 13:05:00', '/storage/2.webp'),
(96, 'Dome Glass Recycling Program Launches', 'dome-glass-recycling-launches', 'Utopia Planitia, 24 Sol-June 2026. A new program will grind and reforge cracked dome panels rather than shipping replacements from distant factories. The recycled glass, engineers say, is nearly as strong as new and far cheaper. With domes covering ever more of the northern plains, the savings could be enormous. Officials frame it as part of a broader push toward a closed-loop economy where nothing is wasted. On a world where every gram is precious, recycling is less an ideal than a necessity.', 'admin@admin', '2026-06-24 07:40:00', '2026-06-24 07:40:00', '/storage/4.webp'),
(98, 'Historic Lander Site Gains Protection', 'historic-lander-site-gains-protection', 'Chryse Planitia, 15 Sol-July 2026. Authorities have declared the site of an early robotic lander a protected monument, fencing off the weathered craft that first proved machines could work on Mars. Historians pushed for the status after tourists began chipping souvenirs from nearby rocks. The lander, silent for decades, now stands as a shrine to the age of exploration. School groups already make pilgrimages across the plain to see where the long human presence on this world quietly began.', 'super.admin@email.com', '2026-07-15 17:30:00', '2026-07-15 17:30:00', '/storage/3.webp'),
(99, 'Algae Vats Boost Oxygen Output', 'algae-vats-boost-oxygen-output', 'Hellas Basin, 24 Sol-July 2026. Settlement engineers have expanded a network of algae vats that scrub carbon and pump out breathable oxygen, easing the load on aging mechanical systems. The green tanks now line the lower levels of several domes, tended by automated arms. Beyond air, the algae yields protein for the food supply, a welcome bonus. Planners call the living machines a model for future habitats, where biology does the quiet work of keeping fragile human outposts alive against the vacuum.', 'admin@admin', '2026-07-24 11:55:00', '2026-07-24 11:55:00', '/storage/2.webp'),
(105, 'Subsurface Tunnels Link Twin Settlements', 'subsurface-tunnels-link-settlements', 'Meridiani Planum, 9 Sol-January 2026. Engineers have completed a network of buried tunnels connecting two long-isolated settlements, sparing travelers the exposed surface crossing that once took a full day. Bored through ancient bedrock, the passages hold their own air and warmth, and rovers now shuttle between the towns in under an hour. Residents on both ends gathered to walk the first stretch together. Planners call it a template for knitting the scattered colonies into something that feels, at last, like a single connected world.', 'super.admin@email.com', '2026-01-09 08:30:00', '2026-01-09 08:30:00', '/storage/3.webp'),
(106, 'Rooftop Gardens Bloom Across Domes', 'rooftop-gardens-bloom-across-domes', 'New Kasei, 21 Sol-January 2026. A movement to green the upper levels of the settlement domes has taken root, with residents tending flowers and vines beneath the sealed canopies. Beyond beauty, the gardens trap moisture and soften the air of the crowded lower quarters. City planners once dismissed the idea as frivolous, but the popularity has changed minds. For colonists raised amid metal and stone, a corridor lined with living green offers a small daily reminder of the world their grandparents left behind.', 'admin@admin', '2026-01-21 14:10:00', '2026-01-21 14:10:00', '/storage/1.webp'),
(107, 'Ice Harvester Fleet Doubles in Size', 'ice-harvester-fleet-doubles', 'North Pole, 4 Sol-February 2026. The fleet of machines that carve water ice from the northern cap has doubled, meeting the thirst of a population that grows every season. The new harvesters run largely unattended, grinding through the layered deposits and ferrying the ice south by rail. Officials say the expansion secures the water supply for a decade. Crews who maintain the machines in the brutal cold are celebrated as unsung heroes, keeping the lifeblood of the settlements flowing from the frozen top of the world.', 'just.admin@email.com', '2026-02-04 09:45:00', '2026-02-04 09:45:00', '/storage/2.webp'),
(108, 'Colony Mints First Local Currency', 'colony-mints-first-local-currency', 'Tharsis, 17 Sol-February 2026. For the first time, the settlements have issued a currency of their own, ending decades of reliance on Earth-backed credits for daily trade. The new script, tied to water and power reserves rather than distant markets, is meant to steady an economy long buffeted by the whims of two worlds. Merchants greeted the change warily but hopefully. Economists call it a coming-of-age moment, a society declaring that its labor and resources hold value on their own terms, no longer measured only against home.', 'super.admin@email.com', '2026-02-17 14:10:00', '2026-02-17 14:10:00', '/storage/4.webp'),
(109, 'Dust Analysis Rewrites Climate History', 'dust-analysis-rewrites-climate-history', 'Planetwide, 1 Sol-March 2026. A sweeping study of dust trapped in polar ice has upended long-held beliefs about the planet\'s climate past, revealing warm, wet spells far more recent than anyone assumed. The findings suggest liquid water may have pooled on the surface within the last few million years, a blink in geological time. Terraforming advocates seized on the news as proof the planet can be coaxed toward warmth again. Skeptics urge caution, but the study has electrified a field that thought its story settled.', 'admin@admin', '2026-03-01 09:45:00', '2026-03-01 09:45:00', '/storage/1.webp'),
(110, 'Zero-G Sports League Holds First Match', 'zero-g-sports-league-first-match', 'Mars Orbit, 13 Sol-March 2026. History was made aboard an orbital habitat as the first professional zero-gravity sports match drew spectators from across the settlements. Players tumbled and spun through a netted arena in a game invented entirely off-world, with rules that would baffle any earthbound athlete. The broadcast reached record audiences on the surface below. Organizers hope the league will give the Martian-born a sport to call their own, born of their unique world rather than imported from the gravity-bound past.', 'just.admin@email.com', '2026-03-13 17:30:00', '2026-03-13 17:30:00', '/storage/3.webp'),
(111, 'Rescue Drones Save Stranded Survey Team', 'rescue-drones-save-survey-team', 'Hellas Basin, 27 Sol-March 2026. A team of geologists stranded by a sudden dust squall has been rescued by a swarm of autonomous drones, guided through near-zero visibility by signals from the crippled rover. The machines delivered air and located the crew within hours, a feat impossible a decade ago. All members returned safely, shaken but unharmed. Rescue officials say the operation proves the worth of the drone fleets that now stand watch over the settlements, ready to reach into storms no human could survive.', 'super.admin@email.com', '2026-03-27 13:40:00', '2026-03-27 13:40:00', '/storage/2.webp'),
(112, 'Vertical Farm Feeds Growing Capital', 'vertical-farm-feeds-growing-capital', 'Tharsis, 7 Sol-April 2026. A towering vertical farm has opened in the heart of the capital, stacking crops floor upon floor under tuned light to feed a population swelling faster than the outlying domes can supply. The structure grows more food per square meter than any surface field, and its harvest reaches markets within hours of picking. Officials hail it as the future of Martian agriculture. In a world where land under a dome is precious, growing upward rather than outward may be the only way to keep pace.', 'admin@admin', '2026-04-07 16:05:00', '2026-04-07 16:05:00', '/storage/4.webp'),
(113, 'Old Rover Retired to Museum Grounds', 'old-rover-retired-to-museum', 'Chryse Planitia, 19 Sol-April 2026. A veteran exploration rover that mapped thousands of kilometers of untouched terrain has been retired and towed to rest on museum grounds. For years it served as the eyes of the early settlers, scouting routes and hunting water long before the domes rose. Engineers who nursed it through countless breakdowns gathered to see it off. The battered machine, still bearing the scratches of a hundred storms, now stands as a monument to the patient exploration that made the settlements possible.', 'just.admin@email.com', '2026-04-19 10:00:00', '2026-04-19 10:00:00', '/storage/1.webp'),
(114, 'Solar Storm Tests Colony Defenses', 'solar-storm-tests-colony-defenses', 'Planetwide, 3 Sol-May 2026. A powerful surge of solar radiation swept the planet this week, and the settlements\' shielding held firm in its sternest test yet. Residents sheltered in reinforced cores as monitors tracked the storm, and no injuries or outages were reported. Engineers had upgraded the defenses only last season, and the timing proved fortunate. Officials credit the calm to years of preparation, though they warn that the sun, unpredictable as ever, will test the colonies again when least expected.', 'super.admin@email.com', '2026-05-03 11:20:00', '2026-05-03 11:20:00', '/storage/3.webp'),
(115, 'Craftsmen Revive Lost Glassblowing Art', 'craftsmen-revive-glassblowing-art', 'Utopia Planitia, 15 Sol-May 2026. A small guild of artisans has revived the ancient craft of glassblowing, working the abundant silica of the northern plains into vessels prized across the settlements. Freed from the pressure of industrial production, they shape each piece by hand, and their swirling, dust-toned wares have become coveted heirlooms. The guild teaches its methods openly, eager to pass the skill to the young. In a society built on machines, the handmade object carries a quiet, growing value all its own.', 'admin@admin', '2026-05-15 14:30:00', '2026-05-15 14:30:00', '/storage/2.webp'),
(116, 'Mapping Mission Charts Hidden Caverns', 'mapping-mission-charts-hidden-caverns', 'Tharsis, 29 Sol-May 2026. A survey drone has charted a vast system of lava caverns beneath the volcanic highlands, spaces large enough to shelter entire settlements from radiation and cold. Geologists had long suspected the tubes existed, but never grasped their scale. Planners are already eyeing them as ready-made homes, needing only sealing and air rather than costly surface domes. The discovery could reshape where and how the colonies grow, drawing future towns down into the protective bones of the planet itself.', 'just.admin@email.com', '2026-05-29 09:10:00', '2026-05-29 09:10:00', '/storage/4.webp'),
(117, 'Youth Council Wins Voting Rights', 'youth-council-wins-voting-rights', 'New Kasei, 11 Sol-June 2026. After a long campaign, the Martian-born youth council has won the right to vote in settlement affairs, a milestone for a generation that has known no other home. Once dismissed as too young to shape policy, they argued that those who will inherit the colonies deserve a voice in building them. The assembly agreed by a narrow margin. Observers call it a turning point, the moment the future citizens of Mars stopped waiting for permission and claimed a share of the world they were born into.', 'super.admin@email.com', '2026-06-11 13:05:00', '2026-06-11 13:05:00', '/storage/1.webp'),
(118, 'Repair Bots Cut Dome Maintenance Costs', 'repair-bots-cut-maintenance-costs', 'Hellas Basin, 23 Sol-June 2026. A new generation of repair robots that crawl the outer skin of the domes has slashed the cost and danger of maintenance, patching micro-fractures before they spread. The machines work through the frigid night when human crews cannot, and report every flaw to a central log. Engineers who once risked the surface in bulky suits now oversee the fleet from warm control rooms. Officials say the savings will fund expansion, turning a grinding chore into a quiet, automated background hum.', 'admin@admin', '2026-06-23 07:40:00', '2026-06-23 07:40:00', '/storage/3.webp'),
(119, 'First Interplanetary Wedding Broadcast', 'first-interplanetary-wedding-broadcast', 'Tharsis, 5 Sol-July 2026. A wedding uniting a Martian settler and an Earthbound partner was broadcast live across both worlds, delays and all, in a ceremony that captivated audiences on two planets. Vows crossed the void with a lag of minutes, turning each exchange into a small act of patience and faith. The couple plan to make their home on Mars. Commentators called the event a symbol of the deepening human ties binding the planets, love stretched across a distance no earlier generation could have imagined.', 'just.admin@email.com', '2026-07-05 10:00:00', '2026-07-05 10:00:00', '/storage/2.webp'),
(120, 'Ancient Meteorite Yields Rare Metals', 'ancient-meteorite-yields-rare-metals', 'Arcadia Planitia, 15 Sol-July 2026. Miners excavating a long-buried meteorite have struck a seam of rare metals prized for advanced electronics, a find that could free the settlements from costly imports. The space rock, older than the planet\'s crust, delivered its treasure billions of years after it fell. Industry has moved quickly to stake claims, and the discovery is expected to spur a wave of local manufacturing. Geologists marvel that the colonies\' future may be forged, in part, from a visitor that crashed here in the deep past.', 'super.admin@email.com', '2026-07-15 17:30:00', '2026-07-15 17:30:00', '/storage/4.webp'),
(121, 'Observatory Detects Distant Exoplanet', 'observatory-detects-distant-exoplanet', 'Tharsis, 24 Sol-July 2026. Astronomers at the summit observatory have detected a rocky world circling a distant star, its signature teased from the steady dark of the Martian night sky. The thin air and stillness that make the mountaintop ideal for observing revealed the planet where earthbound telescopes had failed. Researchers are already planning follow-up studies. For a colony that looks outward by instinct, the find is a source of quiet pride, proof that the frontier of exploration now runs through Mars itself.', 'super.admin@email.com', '2026-07-24 11:55:00', '2026-08-09 21:58:07', '/storage/1.webp'),
(123, 'Recycled Water Meets Safety Standards', 'recycled-water-meets-safety-standards', 'Utopia Planitia, 3 Sol-August 2026. The settlement\'s upgraded water recycling system has passed the strictest purity tests ever applied on Mars, reclaiming nearly every drop that passes through the domes. The achievement eases fears about the long-term safety of drinking water cycled through the same systems for years. Engineers credit a new filtration stage refined entirely on-world. In a place where water is counted molecule by molecule, the certification brings both practical relief and a deeper confidence in the machines that sustain daily life.', 'super.admin@email.com', '2026-08-03 14:45:00', '2026-08-03 14:45:00', '/storage/2.webp'),
(129, 'Magnetic Shield Project Clears First Test', 'magnetic-shield-clears-first-test', 'Mars Orbit, 6 Sol-January 2026. An ambitious plan to wrap the planet in an artificial magnetic field passed its first orbital test this week, as a prototype generator held a stable bubble of shielding for seventy-two hours. Scientists hope a full array could one day deflect the solar wind that has stripped the atmosphere for eons, letting terraforming efforts finally hold ground. Critics call the scale impossibly vast, but supporters point to the steady drumbeat of small successes. For now, a faint shield flickers in the dark, a first proof that the idea is more than a dream.', 'super.admin@email.com', '2026-01-06 08:30:00', '2026-01-06 08:30:00', '/storage/3.webp'),
(130, 'Night Market Revives Old Dome District', 'night-market-revives-old-district', 'New Kasei, 18 Sol-January 2026. A weekly night market has breathed life back into a forgotten quarter of the settlement, drawing crowds to stalls of food, crafts, and salvaged goods beneath strings of warm light. Once a decaying industrial zone, the district now hums with music and barter after dark. Vendors, many of them young, credit cheap rents and a hunger for gathering places. City officials, surprised by the turnout, are studying whether other tired corners of the dome might be coaxed back to life the same way.', 'admin@admin', '2026-01-18 14:10:00', '2026-01-18 14:10:00', '/storage/1.webp'),
(131, 'Deep-Space Telescope Sends First Images', 'deep-space-telescope-first-images', 'Mars Orbit, 3 Sol-February 2026. A telescope assembled in Martian orbit has returned its first images, peering deeper into the cosmos than any instrument launched from Earth. Built far from the glare and haze of the home world, it captures faint galaxies with startling clarity. Astronomers across both planets have hailed the milestone, and observing time is already booked for years. For the settlements, the telescope is a point of pride, evidence that Mars has become not just a place to survive, but a platform from which to study the universe itself.', 'just.admin@email.com', '2026-02-03 09:45:00', '2026-02-03 09:45:00', '/storage/2.webp'),
(132, 'Underground Reservoir Opens for Public Use', 'underground-reservoir-opens', 'Hellas Basin, 16 Sol-February 2026. The vast reservoir carved beneath the basin has opened to supply households directly, ending years of strict rationing across the southern settlements. Fed by melted polar ice and recycled water, the store holds enough to weather even a prolonged drought. Residents lined up to fill the first ceremonial vessels. Engineers who spent a decade hollowing the chamber from bedrock stood quietly at the edge of the crowd. In a world where thirst is never far away, a full reservoir feels less like infrastructure than like salvation.', 'super.admin@email.com', '2026-02-16 14:10:00', '2026-02-16 14:10:00', '/storage/4.webp'),
(133, 'Handwoven Textiles Find Export Market', 'handwoven-textiles-export-market', 'Utopia Planitia, 28 Sol-February 2026. A cooperative of weavers has begun exporting handmade textiles to orbital stations and even back to Earth, where the rough, dust-hued fabrics have become an unlikely luxury. Spun from fibers grown in the northern domes, each piece carries the marks of the loom and the hand. The weavers, once making cloth only for their neighbors, now field orders from two worlds. Their success has sparked talk of a wider craft economy, one where Martian goods are valued not for necessity but for the story woven into them.', 'admin@admin', '2026-02-28 09:45:00', '2026-02-28 09:45:00', '/storage/1.webp'),
(134, 'Emergency Drill Tests Colony Readiness', 'emergency-drill-tests-readiness', 'Planetwide, 10 Sol-March 2026. Settlements across the planet held a coordinated emergency drill this week, simulating a catastrophic dome breach to test evacuation and repair systems. Residents filed calmly into sealed shelters as crews raced to patch mock ruptures against the clock. Officials called the exercise a sobering success, revealing both strengths and gaps in the response. In a place where a single crack can turn deadly in minutes, such drills are grim necessities. Organizers say the lessons learned will shape safety protocols for years to come.', 'just.admin@email.com', '2026-03-10 17:30:00', '2026-03-10 17:30:00', '/storage/3.webp'),
(135, 'Rare Metal Alloy Developed On-World', 'rare-metal-alloy-developed', 'Tharsis, 24 Sol-March 2026. Metallurgists have forged a new alloy using metals mined and refined entirely on Mars, tougher and lighter than anything imported from Earth. The breakthrough, years in the making, could free the settlements from costly shipments and reshape everything from construction to spacecraft. Industry has moved quickly to license the process. Researchers, modest about the achievement, note that the harsh conditions of Mars forced an inventiveness that earthbound labs never needed. What began as a workaround for scarcity may become a genuine advantage.', 'super.admin@email.com', '2026-03-24 13:40:00', '2026-03-24 13:40:00', '/storage/2.webp'),
(136, 'Colony Library Digitizes Rare Records', 'colony-library-digitizes-records', 'New Kasei, 5 Sol-April 2026. The settlement\'s library has completed the digitization of its rarest records, including the handwritten journals of the first settlers, now preserved against the fragility of paper and time. The originals, brittle and fading, chronicle the desperate early years in unflinching detail. Historians call the collection a treasure, a raw account of survival written before anyone knew the venture would last. Copies are now available to every school and household, ensuring that the memory of how the colony began can never be lost to a single accident.', 'admin@admin', '2026-04-05 16:05:00', '2026-04-05 16:05:00', '/storage/4.webp'),
(137, 'Wind-Sculpted Rock Formation Protected', 'wind-sculpted-rock-protected', 'Arcadia Planitia, 17 Sol-April 2026. A striking formation of wind-carved rock, sculpted over eons into delicate arches and spires, has been declared a protected natural landmark after tourists began scaling its fragile stone. The site, long known to survey teams, draws visitors marveling at shapes no earthly wind could carve in the same way. Rangers now patrol its perimeter. Conservationists hail the protection as a sign the settlements are learning to value the planet\'s wild beauty, not just its resources, as they carve out a permanent home.', 'just.admin@email.com', '2026-04-17 10:00:00', '2026-04-17 10:00:00', '/storage/1.webp'),
(138, 'Fusion Reactor Reaches Full Power', 'fusion-reactor-reaches-full-power', 'Tharsis, 2 Sol-May 2026. After years of careful commissioning, the settlements\' first fusion reactor has reached full power, delivering clean energy on a scale that dwarfs the solar arrays it will supplement. The reactor, fueled by hydrogen drawn from polar ice, promises to end the winter power shortages that have long constrained growth. Engineers gathered to watch the output climb to target. Officials call it a turning point, the moment the colonies gained an energy source as ambitious as their dreams, no longer beholden to the fickle sun.', 'super.admin@email.com', '2026-05-02 11:20:00', '2026-05-02 11:20:00', '/storage/3.webp'),
(139, 'Street Musicians Fill Dome Corridors', 'street-musicians-fill-corridors', 'New Kasei, 14 Sol-May 2026. A growing wave of street musicians has transformed the corridors of the settlement, filling once-sterile passages with song drawn from a dozen earthly traditions and a few newly born on Mars. City officials, who once shooed performers away, now grant permits and set aside spaces. Residents linger to listen on their way home. The music, colonists say, softens the hard edges of life under a dome and knits strangers into something like a community. What began as scattered busking has become a cherished part of daily life.', 'admin@admin', '2026-05-14 14:30:00', '2026-05-14 14:30:00', '/storage/2.webp'),
(140, 'Rover Convoy Crosses Uncharted Plateau', 'rover-convoy-crosses-plateau', 'Tharsis, 28 Sol-May 2026. A convoy of pressurized rovers has completed the first crossing of a high, uncharted plateau, mapping terrain no human had ever traversed. The three-week journey battled thin air, jagged rock, and temperatures that froze equipment solid overnight. The crews returned with data that could open a new region to settlement. Mission leaders describe the plateau as bleak and beautiful, a place of long shadows and endless red horizons. For a generation raised inside domes, the crossing was a rare taste of genuine exploration.', 'just.admin@email.com', '2026-05-28 09:10:00', '2026-05-28 09:10:00', '/storage/4.webp'),
(141, 'Colony Adopts Universal Water Credit', 'colony-adopts-water-credit', 'Planetwide, 11 Sol-June 2026. In a sweeping reform, the settlements have adopted a universal water credit guaranteeing every resident a baseline share, regardless of wealth or work. The measure, debated for years, aims to end the quiet inequities that let some hoard while others rationed. Supporters call it a moral necessity on a world where water is life; critics warn of strain on already-tight supplies. The assembly passed it after fierce argument. Whatever its outcome, the reform marks a settlement wrestling openly with what kind of society it wants to be.', 'super.admin@email.com', '2026-06-11 13:05:00', '2026-06-11 13:05:00', '/storage/1.webp'),
(142, 'Greenhouse Blight Contained After Scare', 'greenhouse-blight-contained', 'Arcadia Planitia, 23 Sol-June 2026. A fast-spreading blight that threatened the northern grain domes has been contained after a tense week of quarantine and hurried research. Agronomists traced the infection to a single contaminated batch of seed and moved swiftly to isolate the affected domes. No wider outbreak occurred, and the harvest is expected to survive largely intact. The scare has renewed calls for stricter biosecurity across the plains. In a world where a single blight could starve a settlement, the near miss was a stark reminder of how fragile abundance can be.', 'admin@admin', '2026-06-23 07:40:00', '2026-06-23 07:40:00', '/storage/3.webp'),
(143, 'First Marathon Run Under Open Sky Dome', 'first-marathon-open-sky-dome', 'New Kasei, 5 Sol-July 2026. Runners completed the first marathon held beneath the settlement\'s new transparent sky dome, racing under a filtered view of the actual Martian heavens rather than painted panels. The vast clear canopy, an engineering marvel, let athletes glimpse the pale sun and distant moons as they ran. Spectators packed the route. Organizers, thrilled by the turnout, say the sky dome has changed how residents feel about their sealed world, offering the illusion of open air. For the runners, crossing the line beneath real sky felt like a small liberation.', 'just.admin@email.com', '2026-07-05 10:00:00', '2026-07-05 10:00:00', '/storage/2.webp'),
(144, 'Salvage Crews Recover Lost Supply Pod', 'salvage-crews-recover-supply-pod', 'Chryse Planitia, 15 Sol-July 2026. Salvage crews have recovered a supply pod lost during a botched landing months ago, its cargo of medical equipment intact after weathering the storms of an open plain. The pod, feared destroyed, was located by a survey drone half-buried in drift. Its return eases a shortage that had strained several clinics. The crews, braving harsh terrain to reach it, are being hailed as heroes. In a place where every shipment is precious and every loss keenly felt, recovering the pod was a quiet triumph over an unforgiving world.', 'super.admin@email.com', '2026-07-15 17:30:00', '2026-07-15 17:30:00', '/storage/4.webp'),
(145, 'Colony Debuts Homegrown Film Festival', 'colony-debuts-film-festival', 'Tharsis, 24 Sol-July 2026. The settlements held their first film festival this week, screening works made entirely by Martian filmmakers, many of them born under the domes. The films, ranging from documentaries of the early years to strange dreamlike shorts, drew packed audiences hungry for stories of their own world. Critics praised a fresh voice unbound by earthly convention. Organizers, overwhelmed by submissions, already plan a larger event next year. For a culture still finding itself, the festival was a milestone, proof that the colonies now tell their own tales, in their own way.', 'admin@admin', '2026-07-24 11:55:00', '2026-07-24 11:55:00', '/storage/1.webp'),
(146, 'New Alloy Bridge Spans Rift Valley', 'new-alloy-bridge-spans-rift', 'Valles Marineris, 30 Sol-July 2026. A bridge built from the settlements\' new homegrown alloy has opened across a treacherous rift, its slender span shrugging off winds that would have torn earlier structures apart. The crossing, once a perilous rover detour, now takes minutes. Engineers marvel at how the light, tough metal made the impossible routine. Crowds gathered for the first passage, cheering as vehicles rolled across. The bridge stands as a monument to Martian ingenuity, a structure that could not have been built with imported materials, spanning a chasm the planet itself carved.', 'just.admin@email.com', '2026-07-30 08:20:00', '2026-08-10 07:17:04', '/storage/3.webp'),
(147, 'Sky Dome Observatory Hosts Star Party', 'sky-dome-observatory-star-party', 'New Kasei, 3 Sol-August 2026. Thousands gathered beneath the transparent sky dome for a star party, sharing telescopes and stories under a filtered view of the Martian night. Astronomers pointed out distant planets and the twin moons racing overhead, while children pressed their eyes to eyepieces for the first time. The event, meant to spark interest in science, became a joyful gathering that ran late into the cold night. Organizers say the sky dome has made stargazing communal again, drawing a sealed-in people together to marvel at the vast dark they call home.', 'super.admin@email.com', '2026-08-03 14:45:00', '2026-08-03 14:45:00', '/storage/2.webp'),
(148, 'Settlements Ratify Shared Defense Pact', 'settlements-ratify-defense-pact', 'Tharsis, 7 Sol-August 2026. The major settlements have ratified a shared defense pact, pledging mutual aid against disasters, blackouts, and the rare threat of conflict over scarce resources. The agreement pools emergency crews, supplies, and repair fleets under a joint command reachable within hours. Delegates who once guarded their independence jealously now speak of a common Martian interest. Observers call it a maturing of the colonies from scattered outposts into something like a unified people. On a world that punishes division, the pact is a bet that survival lies in standing together.', 'admin@admin', '2026-08-07 07:41:00', '2026-08-07 07:41:00', '/storage/4.webp');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int UNSIGNED NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user-type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'admin'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `email`, `hash`, `user-type`) VALUES
(2, 'super.admin@email.com', '$2y$10$h8eVw/5vkvhjHfsVsbG.s.ZaDM1raX3IxIZjyt4Nfd7CjA3R4FSuW', 'super_admin'),
(3, 'admin@admin', '$2y$10$1.QGGZkIRtXff/Vl2wu/HuClwFqagMUMSLQEbiNtUpY1udOX/bL9G', 'admin'),
(4, 'just.admin@email.com', '$2y$10$nMfK1TpJuU9.Xt6bnfv6HeaHwvWYMg4uV83OCW7SbWly6y8FMiHLe', 'admin');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `pages`
--
ALTER TABLE `pages`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `uq_users_email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `pages`
--
ALTER TABLE `pages`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=149;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
