INSERT INTO `pages`
(`name`, `slug`, `text`, `author`, `date_published`, `date_updated`, `image_url`) VALUES

                                                                                      ('Ceres Relay Station Goes Live', 'ceres-relay-station-goes-live',
                                                                                       'Ceres, 4 Sol-January 2026. The long-awaited deep-space relay station orbiting the dwarf planet has begun routing traffic between the inner colonies and the outer survey fleets. Engineers spent three years assembling the modular array in vacuum, and its activation cuts message lag to the asteroid belt by nearly a third. Officials call it a quiet revolution for commerce and science alike, binding scattered outposts into a single conversation that no longer waits hours for a reply across the dark.',
                                                                                       'super.admin@email.com', '2026-01-11 08:30:00', '2026-01-11 08:30:00', '/storage/2.webp'),

                                                                                      ('Frost Line Farming Yields Surprise Crop', 'frost-line-farming-surprise-crop',
                                                                                       'Utopia Planitia, 22 Sol-January 2026. Agronomists working the coldest edge of the northern domes have coaxed a hardy root vegetable to thrive where nothing was expected to grow. The strain, engineered over six seasons, tolerates temperature swings that would kill ordinary crops overnight. Settlement kitchens are already experimenting with the harvest, and planners see it as a way to push farming into regions long written off as barren. For a world obsessed with self-sufficiency, every new crop is a small victory.',
                                                                                       'admin@admin', '2026-01-28 14:10:00', '2026-01-28 14:10:00', '/storage/4.webp'),

                                                                                      ('Sandstorm Shelters Pass Safety Review', 'sandstorm-shelters-pass-review',
                                                                                       'Hellas Basin, 6 Sol-February 2026. Inspectors have cleared the basin''s new network of emergency shelters, built to house thousands should a global dust storm sever power to the domes. Each bunker stores air, water, and rations for weeks, and links to neighbors by buried tunnel. The review follows years of anxiety after the great blackout of an earlier decade. Residents say the certification brings a rare sense of security to a place where the sky itself can turn hostile without warning.',
                                                                                       'just.admin@email.com', '2026-02-09 09:45:00', '2026-02-09 09:45:00', '/storage/1.webp'),

                                                                                      ('Orbital Foundry Casts First Beam', 'orbital-foundry-casts-first-beam',
                                                                                       'Mars Orbit, 19 Sol-February 2026. High above the surface, a zero-gravity foundry has poured its first structural beam, drawn from metal mined on Phobos. Freed from gravity, the metal cools into shapes impossible to forge on the ground, longer and lighter than anything a planetary factory could produce. The beam will anchor the next orbital habitat. Engineers describe the moment as the true beginning of building in space, no longer hauling materials up a gravity well at ruinous cost.',
                                                                                       'super.admin@email.com', '2026-02-19 14:10:00', '2026-02-19 14:10:00', '/storage/3.webp'),

                                                                                      ('Language Drift Study Splits Linguists', 'language-drift-study-splits-linguists',
                                                                                       'New Kasei, 2 Sol-March 2026. A study tracking how settlement speech has diverged from Earth tongues has ignited debate among scholars. Younger colonists, researchers find, have coined hundreds of words for phenomena Earth never named, from dust-light to the particular ache of low gravity. Some linguists celebrate a language coming into its own; others fear the drift will one day make the two worlds strangers. Either way, the Martian voice is no longer an echo of the planet it left behind.',
                                                                                       'admin@admin', '2026-03-02 09:45:00', '2026-03-02 09:45:00', '/storage/2.webp'),

                                                                                      ('Canyon Wind Farm Breaks Ground', 'canyon-wind-farm-breaks-ground',
                                                                                       'Valles Marineris, 14 Sol-March 2026. Construction has begun on a wind farm strung along the canyon''s length, where thin air still moves fast enough to turn oversized blades. Skeptics long doubted wind could power anything on Mars, but the canyon''s funneled gusts proved them wrong in trials. If it succeeds, the farm will feed six settlements and prove that the planet''s feeble atmosphere still holds usable energy. The first towers are expected to spin before the end of the year.',
                                                                                       'just.admin@email.com', '2026-03-14 17:30:00', '2026-03-14 17:30:00', '/storage/4.webp'),

                                                                                      ('Archive Ship Returns From Earth', 'archive-ship-returns-from-earth',
                                                                                       'Chryse Planitia, 28 Sol-March 2026. A cargo vessel has arrived bearing a vast archive of Earth''s art, music, and history, requested by settlements eager to preserve their heritage for children who will never visit the home world. Curators are already planning galleries and listening rooms. The shipment weighs almost nothing yet carries centuries of human culture in its data cores. For a society building its own traditions, the archive is both a link to the past and raw material for whatever comes next.',
                                                                                       'super.admin@email.com', '2026-03-28 13:40:00', '2026-03-28 13:40:00', '/storage/1.webp'),

                                                                                      ('Gravity Clinic Reports Breakthrough', 'gravity-clinic-reports-breakthrough',
                                                                                       'Tharsis, 8 Sol-April 2026. A clinic specializing in the ailments of low-gravity life has announced a treatment that restores muscle density lost over years on Mars. Early patients, many of them elderly pioneers, report walking unaided for the first time in seasons. The therapy pairs targeted exercise with a compound developed on-world, a point of pride for local researchers. If it holds up in wider trials, it could transform the prospects of aging in a place the human body was never built for.',
                                                                                       'admin@admin', '2026-04-08 16:05:00', '2026-04-08 16:05:00', '/storage/3.webp'),

                                                                                      ('Meteor Shower Lights Northern Sky', 'meteor-shower-lights-northern-sky',
                                                                                       'Arcadia Planitia, 20 Sol-April 2026. Skywatchers gathered in viewing domes across the north to witness an unusually intense meteor shower, its streaks sharpened by the thin, clear atmosphere. Educators used the event to draw crowds of children into astronomy, and several settlements held rooftop gatherings under sealed canopies. Astronomers traced the debris to a comet that passed generations ago. For a few nights the cold sky put on a show that rivaled anything the old world could offer.',
                                                                                       'just.admin@email.com', '2026-04-20 10:00:00', '2026-04-20 10:00:00', '/storage/2.webp'),

                                                                                      ('Deep Drill Reaches Ancient Aquifer', 'deep-drill-reaches-ancient-aquifer',
                                                                                       'Meridiani Planum, 3 Sol-May 2026. A drilling rig has struck a reservoir of liquid water far beneath the surface, kept unfrozen by the planet''s inner warmth. The find could supply a growing settlement for a century and reshape plans for expansion across the flats. Geologists marvel that the water has waited billions of years in the dark. Mining interests are already circling, and the discovery is likely to test the same water-rights laws that have divided the colonies for a generation.',
                                                                                       'super.admin@email.com', '2026-05-03 11:20:00', '2026-05-03 11:20:00', '/storage/4.webp'),

                                                                                      ('Robotics Fair Draws Record Crowds', 'robotics-fair-draws-record-crowds',
                                                                                       'New Kasei, 16 Sol-May 2026. The annual robotics fair filled its dome to capacity as inventors showed off machines built to survive dust, cold, and vacuum. Student teams competed alongside industry giants, and one homemade rover drew gasps by scaling a wall of loose regolith. The fair has become a proving ground for the tools that keep the settlements alive. Judges say the ingenuity on display, much of it from the Martian-born, points to a future where the colonies invent as much as they import.',
                                                                                       'admin@admin', '2026-05-16 14:30:00', '2026-05-16 14:30:00', '/storage/1.webp'),

                                                                                      ('Polar Ice Survey Completes Season', 'polar-ice-survey-completes-season',
                                                                                       'North Pole, 29 Sol-May 2026. A season-long survey of the northern ice cap has wrapped, returning detailed maps of layered deposits that record the planet''s ancient climate. Researchers waded through data on temperatures and dust cycles stretching back millions of years. The findings will guide both terraforming plans and the hunt for buried water. Team members, weary after months in the cold, describe the cap as a frozen library whose pages they have only begun to read.',
                                                                                       'just.admin@email.com', '2026-05-29 09:10:00', '2026-05-29 09:10:00', '/storage/3.webp'),

                                                                                      ('Trade Council Signs Belt Accord', 'trade-council-signs-belt-accord',
                                                                                       'Tharsis, 11 Sol-June 2026. Delegates have signed a landmark accord opening regular trade routes between Mars and the asteroid belt outposts. The agreement fixes prices for ore and water and promises steadier supplies to both sides. Negotiations dragged for months over shipping rights, but the final handshake was met with relief. Merchants expect the deal to lower costs across the inner system. For settlements long dependent on Earth, a thriving belt trade offers a second lifeline and a taste of independence.',
                                                                                       'super.admin@email.com', '2026-06-11 13:05:00', '2026-06-11 13:05:00', '/storage/2.webp'),

                                                                                      ('Dome Glass Recycling Program Launches', 'dome-glass-recycling-launches',
                                                                                       'Utopia Planitia, 24 Sol-June 2026. A new program will grind and reforge cracked dome panels rather than shipping replacements from distant factories. The recycled glass, engineers say, is nearly as strong as new and far cheaper. With domes covering ever more of the northern plains, the savings could be enormous. Officials frame it as part of a broader push toward a closed-loop economy where nothing is wasted. On a world where every gram is precious, recycling is less an ideal than a necessity.',
                                                                                       'admin@admin', '2026-06-24 07:40:00', '2026-06-24 07:40:00', '/storage/4.webp'),

                                                                                      ('Young Pilots Complete Orbital Training', 'young-pilots-complete-orbital-training',
                                                                                       'Mars Orbit, 5 Sol-July 2026. The first class of Martian-born pilots trained entirely in local space has earned its wings, a milestone for a settlement long reliant on Earth-schooled crews. The graduates flew supply runs to the moons and docked with orbital platforms under the watch of veteran instructors. Officials say home-grown pilots will make the colonies self-sufficient in space. For the young flyers, most of whom have never left Martian space, the achievement is the start of a career among the stars they grew up under.',
                                                                                       'just.admin@email.com', '2026-07-05 10:00:00', '2026-07-05 10:00:00', '/storage/1.webp'),

                                                                                      ('Historic Lander Site Gains Protection', 'historic-lander-site-gains-protection',
                                                                                       'Chryse Planitia, 15 Sol-July 2026. Authorities have declared the site of an early robotic lander a protected monument, fencing off the weathered craft that first proved machines could work on Mars. Historians pushed for the status after tourists began chipping souvenirs from nearby rocks. The lander, silent for decades, now stands as a shrine to the age of exploration. School groups already make pilgrimages across the plain to see where the long human presence on this world quietly began.',
                                                                                       'super.admin@email.com', '2026-07-15 17:30:00', '2026-07-15 17:30:00', '/storage/3.webp'),

                                                                                      ('Algae Vats Boost Oxygen Output', 'algae-vats-boost-oxygen-output',
                                                                                       'Hellas Basin, 24 Sol-July 2026. Settlement engineers have expanded a network of algae vats that scrub carbon and pump out breathable oxygen, easing the load on aging mechanical systems. The green tanks now line the lower levels of several domes, tended by automated arms. Beyond air, the algae yields protein for the food supply, a welcome bonus. Planners call the living machines a model for future habitats, where biology does the quiet work of keeping fragile human outposts alive against the vacuum.',
                                                                                       'admin@admin', '2026-07-24 11:55:00', '2026-07-24 11:55:00', '/storage/2.webp'),

                                                                                      ('Cross-Canyon Bridge Opens to Traffic', 'cross-canyon-bridge-opens',
                                                                                       'Valles Marineris, 30 Sol-July 2026. The longest bridge yet built on Mars has opened, spanning a side canyon that once forced rovers on a day-long detour. Assembled from orbit-forged beams, the structure carries both rail and road across a chasm deep enough to swallow mountains. Crowds gathered at both ends for the first crossing. Engineers call it proof that the canyon''s brutal terrain can be tamed. For the settlements strung along the great rift, the bridge stitches a divided region a little closer together.',
                                                                                       'just.admin@email.com', '2026-07-30 08:20:00', '2026-07-30 08:20:00', '/storage/4.webp'),

                                                                                      ('Museum of Martian Life Opens Doors', 'museum-of-martian-life-opens',
                                                                                       'New Kasei, 3 Sol-August 2026. A museum dedicated to the young history of human life on Mars has opened, gathering the tools, journals, and salvaged machines of the first settlers. Curators arranged the halls to trace the leap from tents to domes to thriving towns. The Martian-born, who make up most visitors, wander exhibits about a hardship they never knew. Officials hope the museum will anchor a shared identity for a people still deciding what it means to belong to this red and demanding world.',
                                                                                       'super.admin@email.com', '2026-08-03 14:45:00', '2026-08-03 14:45:00', '/storage/1.webp'),

                                                                                      ('Weather Network Predicts Calm Season', 'weather-network-predicts-calm-season',
                                                                                       'Planetwide, 7 Sol-August 2026. The expanded atmospheric monitoring network has issued its forecast for the coming storm season, and the outlook is mild, with no global dust events expected. Meteorologists credit new satellites that track pressure and temperature across the whole planet in near real time. Settlements are advised to stay prepared regardless, as local storms can still strike without warning. For a world where weather can bury a town in hours, an accurate forecast is a hard-won comfort worth celebrating.',
                                                                                       'admin@admin', '2026-08-07 07:41:00', '2026-08-07 07:41:00', '/storage/3.webp');